stages:
  - prepare
  - build
  - deploy
  - destroy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  
prepare_job:
  stage: prepare
  tags:
    - shell
  script:
    - 'sed -i "s~mysql-username:~mysql-username: $(echo -n ${MYSQL_USER} | base64) ~g" secret-mysql.yaml'
    - 'sed -i "s~mysql-password:~mysql-password: $(echo -n ${MYSQL_PASSWORD} | base64) ~g" secret-mysql.yaml'
    - 'sed -i "s~mysql-root-password:~mysql-root-password: $(echo -n ${MYSQL_ROOT_PASSWORD} | base64) ~g" secret-mysql.yaml'
  artifacts:
    paths: 
      - ./secret-mysql.yaml
 
tag_php_job:
  stage: build
  tags:
    - shell
  before_script:
  - docker login -u gitlab+deploy-token-2 -p GyFysyfzWzAHeLenEUcC registry.mygta.com 
  script:
    - docker images
    - docker pull registry.mygta.com/alinuxien/mon-projet-php-mysql:master-03264125
    - docker tag registry.mygta.com/alinuxien/mon-projet-php-mysql:master-03264125 $(echo ${IMAGE_TAG})-php
    - docker push $(echo ${IMAGE_TAG})-php

build_mysql_job:
  stage: build
  tags:
    - shell
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $(echo ${IMAGE_TAG})-mysql -f Dockerfile-mysql .
    - docker push $(echo ${IMAGE_TAG})-mysql

deploy_job:
  stage: deploy 
  tags:
    - shell
  script:
    - sudo cp /home/vagrant/.kube/config /home/gitlab-runner/.kube
    - 'sed -i "s~image: PHP_IMAGE~image: $(echo ${IMAGE_TAG})-php ~g" php.yaml'
    - 'sed -i "s~image: MYSQL_IMAGE~image: $(echo ${IMAGE_TAG})-mysql ~g" mysql.yaml'
    - kubectl apply -f secret-mysql.yaml
    - kubectl apply -f mysql.yaml
    - kubectl apply -f configmap.yaml
    - kubectl apply -f php.yaml
  allow_failure: true
  artifacts:
    paths: 
      - ./php.yaml
      - ./mysql.yaml
  environment:
    name: php_mysql_in_kube_pods
    url: http://localhost:30000/
  only:
    - master

destroy_job:
  stage: destroy 
  tags:
    - shell
  script:
    - kubectl delete -f php.yaml
    - kubectl delete -f configmap.yaml
    - kubectl delete -f mysql.yaml
    - kubectl delete -f secret-mysql.yaml
  when: manual
