stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  
build_php_job:
  stage: build
  tags:
    - shell
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG-php -f Dockerfile-php .
    - docker push $IMAGE_TAG-php

build_mysql_job:
  stage: build
  tags:
    - shell
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG-mysql -f Dockerfile-mysql .
    - docker push $IMAGE_TAG-mysql

deploy_job:
  stage: deploy 
  tags:
    - shell
  script:
    - sudo cp /home/vagrant/.kube/config /home/gitlab-runner/.kube
    - 'sed -i "s/image: PHP_IMAGE/image: \$IMAGE_TAG\/php/g" php.yaml'
    - 'sed -i "s/image: MYSQL_IMAGE/image: \$IMAGE_TAG\/mysql/g" mysql.yaml'
    - kubectl apply -f secret-mysql.yaml
    - kubectl apply -f mysql.yaml
    - kubectl apply -f configmap.yaml
    - kubectl apply -f php.yaml
  environment:
    name: php_mysql_in_kube_pods
    url: http://localhost:30000/

